name: Frontend Continuous Integration

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  run-lint-job:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Clean install dependencies
      run: cd /udacity_cloud-devops-engineer_movie-picture-pipeline/starter/frontend && npm ci

    - name: Run linting jobs
      run: cd /udacity_cloud-devops-engineer_movie-picture-pipeline/starter/frontend && npm run lint

  run-test-job:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Clean install dependencies
      run: cd /udacity_cloud-devops-engineer_movie-picture-pipeline/starter/frontend && npm ci

    - name: Run linting jobs
      run: cd /udacity_cloud-devops-engineer_movie-picture-pipeline/starter/frontend && npm run test
      continue-on-error: false

  post-build-job:
    needs: [run-lint-job, run-test-job]
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Clean install dependencies
      run: cd /udacity_cloud-devops-engineer_movie-picture-pipeline/starter/frontend && npm ci

    - name: Run linting jobs
      run: cd /udacity_cloud-devops-engineer_movie-picture-pipeline/starter/frontend && npm run test
      continue-on-error: false

    - name: Build Docker image
      run: cd /udacity_cloud-devops-engineer_movie-picture-pipeline/starter/frontend && docker build -t movie-picture-frontend --build-arg REACT_APP_MOVIE_API_URL=http://localhost:3000 .
